// <auto-generated />
using System;
using ASPNETWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPNETWebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230401205512_NewDataForEntities")]
    partial class NewDataForEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASPNETWebAPI.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "United States",
                            IsoCode = "USD"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Russia",
                            IsoCode = "RUB"
                        },
                        new
                        {
                            Id = 3,
                            Country = "China",
                            IsoCode = "CNY"
                        },
                        new
                        {
                            Id = 4,
                            Country = "India",
                            IsoCode = "INR"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Japan",
                            IsoCode = "JPY"
                        },
                        new
                        {
                            Id = 6,
                            Country = "France",
                            IsoCode = "EUR"
                        });
                });

            modelBuilder.Entity("ASPNETWebAPI.Spending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpendingTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpendingTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Spendings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 250f,
                            Comment = "I bought a new screen",
                            Date = new DateTime(2023, 4, 1, 22, 55, 12, 124, DateTimeKind.Local).AddTicks(8517),
                            SpendingTypeId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 50.5f,
                            Comment = "I had a nice meal at the restaurant",
                            Date = new DateTime(2023, 3, 31, 22, 55, 12, 124, DateTimeKind.Local).AddTicks(8559),
                            SpendingTypeId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 110.9f,
                            Comment = "I went to the best hotel in town",
                            Date = new DateTime(2023, 3, 27, 22, 55, 12, 124, DateTimeKind.Local).AddTicks(8562),
                            SpendingTypeId = 2,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ASPNETWebAPI.SpendingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SpendingTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Restaurant"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hotel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Misc"
                        });
                });

            modelBuilder.Entity("ASPNETWebAPI.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrencyId = 1,
                            FirstName = "Anthony",
                            LastName = "Stark"
                        },
                        new
                        {
                            Id = 2,
                            CurrencyId = 2,
                            FirstName = "Natasha",
                            LastName = "Romanova"
                        });
                });

            modelBuilder.Entity("ASPNETWebAPI.Spending", b =>
                {
                    b.HasOne("ASPNETWebAPI.SpendingType", "SpendingType")
                        .WithMany("Spendings")
                        .HasForeignKey("SpendingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASPNETWebAPI.User", "User")
                        .WithMany("Spendings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpendingType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ASPNETWebAPI.User", b =>
                {
                    b.HasOne("ASPNETWebAPI.Currency", "Currency")
                        .WithMany("Users")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("ASPNETWebAPI.Currency", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ASPNETWebAPI.SpendingType", b =>
                {
                    b.Navigation("Spendings");
                });

            modelBuilder.Entity("ASPNETWebAPI.User", b =>
                {
                    b.Navigation("Spendings");
                });
#pragma warning restore 612, 618
        }
    }
}
